FROM openjdk:oraclelinux8
LABEL maintainer=ervin

ENV APP_FILE=server-a-1.0.jar
ENV APP_HOME=/home/play
ENV SERVER_PORT=8000

COPY $APP_FILE $APP_HOME/

WORKDIR $APP_HOME
EXPOSE $SERVER_PORT

CMD java -jar $APP_FILE